name: api_proyect
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  gsheets: ^0.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
